[ids]
0001:0001

[global]

[main]
# --- combos ---

# change layout
f+j = M-k

# cut
#z+x = C-x

# copy
#x+c = C-c

# paste
#c+v = C-v

# select all
#z+v = C-a

# oneshot's
#shift = oneshot(shift)
#control = oneshot(control)
#leftalt = oneshot(alt)
#rightalt = oneshot(altgr)

# overloader's
tab = overloadi(tab, overloadt2(nav_layer, tab, 100), 150)
#s = overloadi(s, overloadt2(sys_layer, s, 100), 150)
capslock = overloadt(control, esc, 100)
#enter    = overloadt(control, enter, 150)

# --- layers ---
[nav_layer]

# vim-style navigation
h = left
j = down
k = up
l = right

# page nav
u = pageup
i = pagedown

# kde overview
w = M-w

# brave tab search window
q = A-q

# action keys
a = esc
; = enter
o = backspace
[ = delete
space = A-space
capslock = capslock
d = scrolllock

#[sys_layer]
#h = mute
#j = volumedown
#k = volumeup
#l = brightnessdown
#; = brightnessup
#o = M-l
#/ = M-/

# workaround to make activation of Ctrl+F immediate 
#[control]
#f = C-f
#s = C-s
